trigger:
  branches:
    include:
    - master
    - releases/*
    - features/*
    exclude:
    - releases/old*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'test'
    organization: 'softwarehero'
    scannerMode: 'MSBuild'
    projectKey: 'SHMS'
    projectName: 'Mailing Service'
    
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 3.1.100
    performMultiLevelLookup: true
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*UnitTests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    codeCoverageEnabled: true
    otherConsoleOptions: '/framework:".NETCoreApp,Version=3.1"'
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'